/*
 * @Author: ghost
 * @Date: 2018-07-03 17:45:01
 * @Last Modified by:   aroop.ghosh@tarento.com
 * @Last Modified time: 2018-07-03 17:45:01
 */
const constants = {
    APISTATUS: 'APISTATUS',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    QNA: 'QNA',
    AUTO_ML: 'AUTO_ML',
    NMT: 'NMT',
    NMTSP: 'NMTSP',
    CREATE_CORPUS: 'CREATE_CORPUS',
    CREATE_TRANSLATIONS: 'CREATE_TRANSLATIONS',
    BENCHMARK: 'BENCHMARK',
    FETCH_CORP: 'FETCH_CORP',
    FETCH_SENTENCES: 'FETCH_SENTENCES',
    FETCH_TRANSLATION_SENTENCES: 'FETCH_TRANSLATION_SENTENCES',
    FETCH_TRANSLATIONS: 'FETCH_TRANSLATIONS',
    UPDATE_SENTENCE:'UPDATE_SENTENCE',
    UPDATE_SENTENCE_STATUS:'UPDATE_SENTENCE_STATUS',
    UPDATE_SENTENCE_GRADE:'UPDATE_SENTENCE_GRADE'
};

export default constants;
